server {
    listen 80;
    
    root /usr/share/nginx/html;
    index IndexMain/index.html;
    
    location = / {
        try_files /IndexMain/index.html =404;
    }
    
    location / {
        try_files $uri $uri/ =404;
    }
}