sonar.projectKey=puj-course_FIS_2610_3513_G2
sonar.organization=puj-course
sonar.sources=src,prisma
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=\
  src/main.ts,\
  src/app.module.ts,\
  src/ingredientes/ingredientes.controller.ts,\
  src/ingredientes/ingredientes.service.ts,\
  src/moderacion/metricas.middleware.ts,\
  src/moderacion/metricas.service.ts,\
  src/SMS/sms.controller.ts,\
  src/SMS/sms.service.ts,\
  src/telegram/telegram.controller.ts,\
  src/telegram/telegram.service.ts,\
  src/moderacion/facades/notificaciones.facade.ts,\
  src/usuarios/usuarios.controller.ts