sonar.projectKey=puj-course_FIS_2610_3513_GX
sonar.organization=puj-course

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
