sonar.projectKey=puj-course_FIS_2610_3513_G2
sonar.organization=puj-course
sonar.sources=src,prisma
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=\
  src/main.ts,\
  src/app.module.ts,\
  src/ingredientes/ingredientes.controller.ts,\
  src/ingredientes/flyweight/ingrediente-flyweight.factory.ts,\
  src/ingredientes/flyweight/ingrediente.flyweight.ts,\
  src/moderacion/metricas.middleware.ts,\
  src/moderacion/moderacion.controller.ts,\
  src/moderacion/moderacion.module.ts,\
  src/moderacion/facades/notificaciones.facade.ts,\
  src/moderacion/handlers/moderacion.handler.ts,\
  src/recetas/recetas.controller.ts,\
  src/recetas/builder/recetaImageless.builder.ts,\
  src/SMS/sms.controller.ts,\
  src/telegram/telegram.controller.ts,\
  src/telegram/NotificacionesFacade.ts,\
  src/usuarios/usuarios.controller.ts,\
  prisma/prisma.service.ts